# Generated by Django 4.1.7 on 2023-05-23 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import skillport.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('links', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, default='default/default_pfp.png', upload_to=skillport.models.user_media_path)),
                ('device', models.CharField(blank=True, max_length=200, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=30)),
                ('subscriptions', models.ManyToManyField(blank=True, to='skillport.person')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='default/default_pfp.png', upload_to=skillport.models.project_media_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='skillport.person')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skillport.projecttype')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='skillport.person')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='skillport.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='skillport.project')),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(blank=True, default='default/default_pfp.png', upload_to=skillport.models.additional_media_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='skillport.project')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_image', models.ImageField(blank=True, default='default/default_pfp.png', upload_to=skillport.models.additional_media_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='skillport.project')),
            ],
        ),
    ]
