# Generated by Django 4.1.7 on 2023-05-10 17:58

from django.db import migrations, models
import skillport.models


class Migration(migrations.Migration):

    dependencies = [
        ('skillport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default/default_pfp.png', upload_to=skillport.models.project_media_path),
        ),
    ]
