# Generated by Django 4.1.7 on 2023-05-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='guest_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
