# Generated by Django 4.1.7 on 2023-05-10 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillport', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subscriptions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
